### ISSUE TITLE
[Not an issue but a question] Port to edge 30 ultra

### ISSUE THREAD

**Issue by gabriel-hurtado** [Pranav-Talmale/android_device_motorola_dubai-twrp#4]
I forked your repo and tried to modify it for the edge 30 ultra.

Is there anything more I should do before building, other than changing all the occurrences of "dubai" to "eqs" ? Maybe I should delete the prebuilt kernel ?

**Comment by Pranav-Talmale** [comment]
1. Replace every instance of dubai with eqs
2. Change kernel 
3. Change Kernel modules (recovery/root/vendor/lib)
4. Also when adding eqs kernel modules, change the 
     list of modules to be loaded in BoardConfig.mk.
6. Change firmware (recovery/root/vendor/firmware)
7. Change ueventd.rc and init.recovery.usb.rc from stock ROM

And you should be pretty-much done porting

**Comment by Pranav-Talmale** [comment]
I don't have any idea in the kernel area of things. I am not the right person to be asked this sort of question
